unstable_features = true

comment_width = 90
wrap_comments = true

array_width = 40
attr_fn_like_width = 1
fn_call_width = 5
struct_lit_width = 2
struct_variant_width = 2
chain_width = 2
single_line_if_else_max_width = 10

max_width = 60
use_small_heuristics = 'max'

binop_separator = "Front"

blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
